### ISSUE TITLE
Log file wiped on app start

### ISSUE THREAD

**Issue by lorenblue** [needle-mirror/com.unity.logging#1]
Hello,

Every time I restart my app, my log file gets wiped. I cannot imagine that this is the intended behavior of the package, so I apologize if I have made a silly error somehow.

Code for initializing logger:

```
private Logger _logger;

        private void Start()
        {
            _logger = new LoggerConfig()
                .OutputTemplate("{Timestamp} - {Message}")
                .WriteTo.File(Path.Combine(Application.persistentDataPath, "exercise_log.txt"))
                .CaptureStacktrace(false)
                .CreateLogger();
        }
```
Code for using logger:

`Log.To(_logger).Info("{action} -> {exerciseName} ({location}).", action, exerciseName, location);`

**Comment by hybridherbst** [comment]
Hey, please report a bug to Unity. 
We're only mirroring the packages for convenience of seeing what has been updated and why.

That being said, it looks like you're always writing to the same file in yoiur code, you likely want the timestamp as part of the filename to avoid overwriting.
